language:
  - node_js
node_js:
  - 9.5
cache:
  directories:
    - node_modules
    - packages/blockchain-info-components/node_modules
    - packages/blockchain-wallet-v4/node_modules
    - packages/blockchain-wallet-v4-frontend/node_modules
before_install:
  - npm install -g lerna yarn
install:
  - yarn && lerna bootstrap
script:
  - 'if [ "$TRAVIS_EVENT_TYPE" != "cron" ]; then
      # normal build
      yarn lint;
      yarn ci:test;
      yarn ci:build:prod;
    else
      # cron job build to update unit test coverage
      yarn ci:coverage;
      ./node_modules/.bin/istanbul-coveralls;
    fi;'
before_deploy:
  - 'if [ "$TRAVIS_EVENT_TYPE" != "cron" ]; then
      zip -r build.zip ./dist
    fi;'
