language:
  - node_js
node_js:
  - 9.5
cache:
  directories:
    - node_modules
    - packages/blockchain-info-components/node_modules
    - packages/blockchain-wallet-v4/node_modules
    - packages/blockchain-wallet-v4-frontend/node_modules
before_install:
  - npm install -g lerna yarn
install:
  - yarn && lerna bootstrap
script:
  - if [ $TRAVIS_EVENT_TYPE == "push" ] && [ $TRAVIS_BRANCH == "master" ]; then
      # full build with test coverage reporting for merges into master
      yarn lint;
      yarn ci:coverage;
      ./node_modules/.bin/istanbul-coveralls;
      yarn ci:build:prod;
    else
      # quick build for commits and PRs
      yarn lint;
      yarn ci:test;
      yarn ci:build;
    fi
before_deploy:
  - if [ $TRAVIS_EVENT_TYPE == "push" ] && [ $TRAVIS_BRANCH == "master" ]; then
      zip -r build.zip ./dist
    fi
#deploy:
#  - echo "*** DEPLOY ***"

