language:
  - node_js

node_js:
  - 9.5

cache:
  directories:
    - node_modules
    - packages/blockchain-info-components/node_modules
    - packages/blockchain-wallet-v4/node_modules
    - packages/blockchain-wallet-v4-frontend/node_modules

before_install:
  - npm install -g lerna yarn

install:
  - yarn && lerna bootstrap

stages:
  - name: commit-build
    if: type IN (push)

  - name: pr-build
    if: type IN (pull_request)

  - name: coverage-build
    if: type IN (cron)

jobs:
  include:
    - stage: commit-build
      script:
        - yarn lint
        - yarn ci:test

    - stage: pr-build
      script:
        - yarn lint
        - yarn ci:test
        - yarn ci:build:prod

    - stage: coverage-build
      script:
        - yarn ci:coverage
        - ./node_modules/.bin/istanbul-coveralls
