language:
  - node_js
node_js:
  - 9.5
cache:
  directories:
    - node_modules
    - packages/blockchain-info-components/node_modules
    - packages/blockchain-wallet-v4/node_modules
    - packages/blockchain-wallet-v4-frontend/node_modules
before_install:
  - npm install -g lerna yarn
install:
  - yarn && lerna bootstrap
script:
  # commit quick build
  - if [ $TRAVIS_EVENT_TYPE == "push"]; then yarn lint; yarn ci:test; fi
  # pull request build
  - if [ $TRAVIS_EVENT_TYPE == "pull_request" ]; then yarn lint; yarn ci:test; yarn ci:build:prod; fi
  # coverage report build
  - if [ $TRAVIS_EVENT_TYPE == "cron"]; then yarn ci:coverage; ./node_modules/.bin/istanbul-coveralls; fi
