language:
  - node_js

node_js:
  - 9.5

cache:
  directories:
    - node_modules
    - packages/blockchain-info-components/node_modules
    - packages/blockchain-wallet-v4/node_modules
    - packages/blockchain-wallet-v4-frontend/node_modules

before_install:
  - npm install -g lerna yarn

install:
  - yarn && lerna bootstrap

stages:
  - name: commit-build
    if: type IN (push) AND NOT branch = master

  - name: coverage-build
    if: type IN (cron)

  - name: pr-build
    if: type IN (pull_request)

  - name: prod-deploy-build
    if: type IN (push) AND branch = master

jobs:
  include:
    - stage: commit-build
      script:
        - echo "** COMMIT BUILD **"
        - yarn lint
        - yarn ci:test

    - stage: coverage-build
      script:
        - echo "** COVERAGE BUILD **"
        - yarn ci:coverage
        - ./node_modules/.bin/istanbul-coveralls

    - stage: pr-build
      script:
        - echo "** PR BUILD **"
        - yarn lint
        - yarn ci:test
        - yarn ci:build:prod

    - stage: prod-deploy-build
      script:
        - echo "** PROD DEPLOY BUILD **"
        - yarn lint
        - yarn ci:test
        - yarn ci:build:prod
