version: 2

references:
  workspace_root: &workspace_root
      /home/circleci/blockchain-wallet-v4-frontend

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  container_config: &container_config
    working_directory: /home/circleci/blockchain-wallet-v4-frontend
    docker:
      - image: circleci/node:10.6-jessie-browsers

  npm_cache_key: &npm_cache_key
    v1-dependency-npm-{{ checksum "yarn.lock" }}
  npm_backup_cache_key: &npm_backup_cache_key
    v1-dependency-npm

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key
        - *npm_backup_cache_key

  restore_repo: &restore_repo
      restore_cache:
        keys:
          - v1-repo-{{ .Branch }}-{{ .Revision }}
          - v1-repo-{{ .Branch }}
          - v1-repo

jobs:
  checkout_code:
    <<: *container_config
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
  install_deps:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - run:
          name: Install Dependencies
          command: npm install yarn babel-cli rimraf cross-env && yarn
      - save_cache:
          key: *npm_cache_key
          paths:
            - /home/circleci/blockchain-wallet-v4-frontend/node_modules
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - .
  lint_code:
    <<: *container_config
    steps:
      - *attach_workspace
      - run:
          name: Lint Code
          command: yarn lint
  test_code:
    <<: *container_config
    steps:
      - *attach_workspace
      - run:
          name: Test Code
          command: yarn ci:test
  coverage:
    <<: *container_config
    steps:
      - *attach_workspace
      - run:
          name: Code Coverage
          command: yarn coverage

workflows:
  version: 2
  pull_request:
    jobs:
      - checkout_code
      - install_deps:
          requires:
            - checkout_code
      - lint_code:
          requires:
            - install_deps
      - test_code:
          requires:
            - install_deps
  test_coverage:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - development
    jobs:
      - install
      - coverage
