version: 2

references:
  workspace_root: &workspace_root /home/circleci

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  container_config: &container_config
    working_directory: /home/circleci/blockchain-wallet-v4-frontend
    docker:
      - image: circleci/node:10.12.0-jessie-browsers

jobs:
  pull_code:
    <<: *container_config
    steps:
      - checkout
  npm_install:
    <<: *container_config
    steps:
      - run:
          name: Install App Dependencies
          command: sudo npm install -g yarn@1.12.1 && yarn
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - blockchain-wallet-v4-frontend
  lint:
    <<: *container_config
    steps:
      - *attach_workspace
      - run:
          name: Lint Code
          command: yarn lint
  test:
    <<: *container_config
    steps:
      - *attach_workspace
      - run:
          name: Test Code
          command: yarn ci:test:build && yarn ci:test:core:components && yarn ci:test:frontend
  coverage:
    <<: *container_config
    steps:
      - *attach_workspace
      - run:
          name: Code Coverage
          command: yarn ci:test:build && yarn ci:coverage:components && yarn ci:coverage:core && yarn ci:coverage:frontend
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - blockchain-wallet-v4-frontend
  coverage_report_to_coveralls:
    <<: *container_config
    steps:
      - *attach_workspace
      - run:
          name: Report Code Coverage
          command: yarn ci:coverage:report
workflows:
  version: 2

  pull_request:
    jobs:
      - pull_code
      - npm_install:
          requires:
            - pull_code
      - lint:
          requires:
            - npm_install
      - test:
          requires:
            - npm_install
      - coverage:
          requires:
            - test
      - coverage_report_to_coveralls:
          requires:
            - coverage
