version: 2

jobs:
  install:
    docker:
     - image: circleci/node:10.6-jessie-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - npm-deps-{{ .Branch }}-
            - npm-deps-
      - run:
          name: Install
          command: npm install yarn babel-cli rimraf cross-env && yarn
      - save_cache:
          key: npm-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  lint:
    docker:
      - image: circleci/node:10.6-jessie-browsers
    steps:
      - restore_cache:
          keys:
            - npm-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - npm-deps-{{ .Branch }}-
            - npm-deps-
      - run:
          name: Lint
          command: yarn lint
  test:
    docker:
      - image: circleci/node:10.6-jessie-browsers
    steps:
      - restore_cache:
          keys:
            - npm-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - npm-deps-{{ .Branch }}-
            - npm-deps-
      - run:
          name: Test
          command: yarn ci:test
  coverage:
    docker:
      - image: circleci/node:10.6-jessie-browsers
    steps:
      - restore_cache:
          keys:
            - npm-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - npm-deps-{{ .Branch }}-
            - npm-deps-
      - run:
          name: Coverage
          command: yarn coverage

workflows:
  version: 2
  pull_request:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
  test_coverage:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - development
    jobs:
      - install
      - coverage
