version: 2

jobs:
  checkout_code:
    docker:
      - image: circleci/node:10.6-jessie-browsers
    working_directory: ~/blockchain-wallet-v4-frontend
    steps:
      - checkout
      - save_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/blockchain-wallet-v4-frontend
  install_deps:
    docker:
     - image: circleci/node:10.6-jessie-browsers
    working_directory: ~/blockchain-wallet-v4-frontend
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}-
            - yarn-cache-
      - restore_cache:
          keys:
            - npm-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - npm-deps-{{ .Branch }}-
            - npm-deps-
      - run:
          name: Install Dependencies
          command: npm install yarn babel-cli rimraf cross-env && yarn
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/blockchain-wallet-v4-frontend/.cache/yarn
      - save_cache:
          key: npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - ~/blockchain-wallet-v4-frontend/node_modules
  lint_code:
    docker:
      - image: circleci/node:10.6-jessie-browsers
    working_directory: ~/blockchain-wallet-v4-frontend
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}-
            - yarn-cache-
      - restore_cache:
          keys:
            - npm-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - npm-deps-{{ .Branch }}-
            - npm-deps-
      - run: yarn
      - run:
          name: Lint Code
          command: yarn lint
  test_code:
    docker:
      - image: circleci/node:10.6-jessie-browsers
    working_directory: ~/blockchain-wallet-v4-frontend
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}-
            - yarn-cache-
      - restore_cache:
          keys:
            - npm-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - npm-deps-{{ .Branch }}-
            - npm-deps-
      - run: yarn
      - run:
          name: Test Code
          command: yarn ci:test
  coverage:
    docker:
      - image: circleci/node:10.6-jessie-browsers
    working_directory: ~/blockchain-wallet-v4-frontend
    steps:
      - run:
          name: Code Coverage
          command: yarn coverage

workflows:
  version: 2
  pull_request:
    jobs:
      - checkout_code
      - install_deps:
          requires:
            - checkout_code
      - lint_code:
          requires:
            - install_deps
      - test_code:
          requires:
            - install_deps
  test_coverage:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - development
    jobs:
      - install
      - coverage
