version: 2

references:
  workspace_root: &workspace_root ~/blockchain-wallet-v4-frontend

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  container_config: &container_config
    working_directory: ~/blockchain-wallet-v4-frontend
    docker:
      - image: circleci/node:12.18-browsers

  npm_cache_key: &npm_cache_key v15-dependency-npm-{{ checksum "yarn.lock" }}

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key
        - v15-dependency-npm

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v15-repo-{{ .Branch }}-{{ .Revision }}
        - v15-repo-{{ .Branch }}
        - v15-repo

jobs:
  pull_code:
    <<: *container_config
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v15-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
  npm_install:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - run:
          name: Install App Dependencies
          command: sudo ./setup.sh
      - save_cache:
          key: *npm_cache_key
          paths:
            - ./node_modules
  lint:
    <<: *container_config
    steps:
      - *attach_workspace
      - run:
          name: Lint Code
          command: yarn ci:lint
  test:
    <<: *container_config
    steps:
      - *attach_workspace
      - run:
          name: Test Code
          command: yarn ci:test:build && yarn ci:test:core:components && yarn ci:test:frontend
  codechecks:
    <<: *container_config
    steps:
      - *attach_workspace
      - run:
          name: Run Codechecks
          command: yarn codechecks
workflows:
  version: 2

  pull_request:
    jobs:
      - pull_code
      - npm_install:
          requires:
            - pull_code
      - lint:
          requires:
            - npm_install
      - test:
          requires:
            - npm_install
      - codechecks:
          requires:
            - npm_install
